---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install common packages
  apt:
    name:
      - vim
      - curl
      - git
      - htop
    state: present
